# Generated by Django 3.1.3 on 2020-11-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('name', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
