# Generated by Django 3.1.3 on 2021-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210205_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_choices',
            field=models.CharField(choices=[('DW', 'Dragons and Witches Novels'), ('FT', 'Fantasy Novels'), ('HOTN', 'Heros of the Night Novels'), ('JG', 'Jungle Novels'), ('TL', 'Travel Novels'), ('IS', 'Into Space Novels')], default='FT', max_length=32),
        ),
    ]
