# Generated by Django 3.1.3 on 2021-02-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_book_book_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_choices',
            new_name='book_category_novel',
        ),
    ]
