# Generated by Django 3.1.3 on 2021-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210205_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='full_book',
            field=models.TextField(default='Write novel here', max_length=10000),
        ),
    ]
