# Generated by Django 3.1.3 on 2021-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210205_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about_author',
            field=models.TextField(default='Write about author', max_length=900),
        ),
    ]
